[2023-04-11T14:55:24.219+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T13:54:00+00:00 [queued]>
[2023-04-11T14:55:24.230+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T13:54:00+00:00 [queued]>
[2023-04-11T14:55:24.230+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T14:55:24.231+0000] {taskinstance.py:1283} INFO - Starting attempt 4 of 4
[2023-04-11T14:55:24.232+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T14:55:24.251+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-11 13:54:00+00:00
[2023-04-11T14:55:24.257+0000] {standard_task_runner.py:55} INFO - Started process 2343 to run task
[2023-04-11T14:55:24.260+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-11T13:54:00+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpbbrqoayo']
[2023-04-11T14:55:24.262+0000] {standard_task_runner.py:83} INFO - Job 232: Subtask id_2
[2023-04-11T14:55:24.318+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 232 for task id_2 ([Errno 5] Input/output error: '/opt/airflow/logs/dag_id=execute_24hr_data_scrape/run_id=scheduled__2023-04-11T13:54:00+00:00/task_id=id_2/attempt=4.log'; 2343)
[2023-04-11T14:55:24.352+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-11T14:55:24.370+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
